name: Discord Auto Announcement

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.RELEASE_UPDATE_ANNOUNCEMENT_WEBHOOK }}
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\":\"@everyone 更新${{ github.event.release.tag_name }} (倉庫更新約有五分鐘延遲) \n\n${{ github.event.release.body }}\n\n下載 APK：${{ github.event.release.assets[0].browser_download_url }}\"}" \
               $DISCORD_WEBHOOK_URL
