name: Discord Auto Announcement

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.RELEASE_UPDATE_ANNOUNCEMENT_WEBHOOK }}
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '${{ toJson({content: format("@ 更新{} (倉庫更新約有五分鐘延遲)\n\n{}\n\n下載 APK：{}", github.event.release.tag_name, github.event.release.body, github.event.release.assets[0].browser_download_url)}) }}' \
               $DISCORD_WEBHOOK_URL
